stages:
  - build
  - test

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  tags:
    - ansible
  script:
    - npm install --verbose
    - pkg .
#  artifacts:
#    paths:
#      - node_modules/

testing_testing:
  stage: test
  script: npm test