stages:
  - build
  - test

tags:
    - ansible

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - npm install
    - pkg .
  artifacts:
    paths:
      - node_modules/

testing_testing:
  stage: test
  script: npm test